s|%app_env%|production|g
s|%app_key%|base64:RuQ6RDvlEbjoYSSfX5CgNnvApGMtsHC/0GOOwFXYw/Y=|g
s|%app_debug%|false|g
s|%app_url%|https://admin.staging.rem.work|g
s|%front_url%|https://staging.rem.work|g
s|%log_channel%|daily|g
s|%db_host%|127.0.0.1|g
s|%db_port%|5432|g
s|%db_database%|rem_work_staging|g
s|%db_username%|rem_work_staging|g
s|%db_password%|5@Vf0XZR5vPw|g
s|%broadcast_driver%|log|g
s|%cache_driver%|file|g
s|%queue_connection%|sync|g
s|%session_driver%|file|g
s|%session_lifetime%|120|g
